FROM mcr.microsoft.com/playwright:v1.32.3-jammy
USER root
RUN mkdir /playwrightTests
COPY . /playwrightTests
WORKDIR /playwrightTests/playwrightTesting/
# RUN npm ci
RUN npm install
RUN npx @playwright/test install
RUN npx playwright install-deps
CMD ["npm", "run", "triggerheadless"]